import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Serveractions with hCaptcha',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="bg-cyan-400">
          <h1 className="text-white text-4xl py-2 px-6">{metadata.title}</h1>
        </header>
        <main className='px-10 py-8'>
          {children}
        </main>
      </body>
    </html>
  )
}
